export const conceptCards = [
  {
    id: 'claim',
    title: '주장',
    definition: '참이거나 거짓일 수 있는 중심 생각입니다.',
    example: '좋은 삶에는 쾌락보다 의미가 더 중요하다.',
    commonMistake: '감탄, 질문, 명령을 주장으로 착각하기 쉽습니다.',
    quiz: '"왜 우리는 약속을 지켜야 하는가?"는 주장일까요?',
    answer: '아닙니다. 질문입니다. "우리는 약속을 지켜야 한다"가 주장입니다.',
  },
  {
    id: 'reason',
    title: '근거',
    definition: '주장을 받아들여야 하는 이유입니다.',
    example: '약속을 어기면 신뢰가 무너지기 때문에 약속을 지켜야 한다.',
    commonMistake: '주장을 반복하는 말을 근거로 착각하기 쉽습니다.',
    quiz: '근거는 결론을 지지해야 할까요?',
    answer: '네. 근거는 결론을 믿을 이유를 제공해야 합니다.',
  },
  {
    id: 'hidden-premise',
    title: '숨은 전제',
    definition: '글에 직접 쓰이지 않았지만 논증이 성립하려면 필요한 가정입니다.',
    example: '쾌락이 많을수록 좋은 삶이다. 숨은 전제: 좋은 삶은 쾌락의 양으로 판단된다.',
    commonMistake: '문장에 보이는 근거만 보고 배경 가정을 놓치기 쉽습니다.',
    quiz: '숨은 전제는 항상 명시되어 있을까요?',
    answer: '아닙니다. 그래서 직접 찾아내야 합니다.',
  },
  {
    id: 'counterargument',
    title: '반론',
    definition: '상대 주장의 약점이나 빠진 조건을 드러내는 응답입니다.',
    example: '쾌락이 중요해도 의미 없는 쾌락만 있는 삶은 좋은 삶이라고 보기 어렵다.',
    commonMistake: '상대방을 공격하는 말을 반론으로 착각하기 쉽습니다.',
    quiz: '좋은 반론은 무엇을 겨냥해야 할까요?',
    answer: '사람이 아니라 주장, 근거, 전제, 추론의 약점을 겨냥해야 합니다.',
  },
  {
    id: 'deduction',
    title: '연역',
    definition: '전제가 참이면 결론도 반드시 참이어야 하는 추론입니다.',
    example: '모든 인간은 죽는다. 소크라테스는 인간이다. 그러므로 소크라테스는 죽는다.',
    commonMistake: '결론이 그럴듯하다는 이유만으로 연역이 타당하다고 보기 쉽습니다.',
    quiz: '연역은 가능성이 아니라 필연성을 따질까요?',
    answer: '네. 전제들이 참일 때 결론이 반드시 따라오는지를 봅니다.',
  },
  {
    id: 'fallacy',
    title: '논리 오류',
    definition: '겉보기에는 그럴듯하지만 추론 구조에 문제가 있는 논증입니다.',
    example: '유명인이 말했다. 그러므로 참이다.',
    commonMistake: '내가 동의하지 않는 주장을 모두 오류라고 부르기 쉽습니다.',
    quiz: '권위자의 말은 언제나 오류일까요?',
    answer: '아닙니다. 관련 전문성과 근거가 있을 때는 참고할 수 있습니다.',
  },
];

export const trainingPrompts = [
  {
    id: 'pleasure-life',
    topic: '행복과 쾌락',
    level: 'beginner',
    argumentText: '행복은 쾌락의 총량이다. 그러므로 더 많은 쾌락을 주는 삶이 더 좋은 삶이다.',
    modelClaim: '더 많은 쾌락을 주는 삶이 더 좋은 삶이다.',
    modelReasons: ['행복은 쾌락의 총량이다.'],
    hiddenPremise: '좋은 삶은 행복의 양으로 판단되며, 행복은 쾌락만으로 구성된다.',
    weakness: '의미, 관계, 인격, 장기적 만족 같은 요소를 배제한다.',
    sampleCounterargument: '쾌락이 많아도 의미와 신뢰가 없는 삶은 좋은 삶이라고 보기 어렵다.',
    samplePosition:
      '쾌락은 좋은 삶의 중요한 요소다. 그러나 좋은 삶을 쾌락만으로 판단하면 의미와 관계를 놓친다. 따라서 쾌락은 행복의 일부이지 전체는 아니다.',
  },
  {
    id: 'promise-trust',
    topic: '약속과 신뢰',
    level: 'beginner',
    argumentText: '약속을 어기면 신뢰가 무너진다. 사회는 신뢰 없이는 유지될 수 없다. 그러므로 우리는 약속을 지켜야 한다.',
    modelClaim: '우리는 약속을 지켜야 한다.',
    modelReasons: ['약속을 어기면 신뢰가 무너진다.', '사회는 신뢰 없이는 유지될 수 없다.'],
    hiddenPremise: '사회 유지에 필요한 행동은 도덕적으로 해야 할 행동이다.',
    weakness: '예외 상황, 부당한 약속, 더 큰 피해를 막기 위한 위반을 다루지 않는다.',
    sampleCounterargument: '모든 약속을 지켜야 하는 것은 아니다. 부당한 약속은 깨는 것이 더 도덕적일 수 있다.',
    samplePosition:
      '약속은 신뢰를 만들기 때문에 기본적으로 지켜야 한다. 하지만 약속의 내용이 부당하거나 타인에게 큰 피해를 준다면 예외가 필요하다. 그래서 약속의 의무는 강하지만 절대적이지는 않다.',
  },
  {
    id: 'freedom-choice',
    topic: '자유와 선택',
    level: 'beginner',
    argumentText: '선택지가 많을수록 사람은 더 자유롭다. 현대인은 과거보다 선택지가 많다. 그러므로 현대인은 과거 사람보다 더 자유롭다.',
    modelClaim: '현대인은 과거 사람보다 더 자유롭다.',
    modelReasons: ['선택지가 많을수록 사람은 더 자유롭다.', '현대인은 과거보다 선택지가 많다.'],
    hiddenPremise: '자유는 선택지의 수로만 판단된다.',
    weakness: '선택 능력, 사회적 압박, 정보 과부하, 경제적 조건을 고려하지 않는다.',
    sampleCounterargument: '선택지가 많아도 실제로 선택할 능력이나 조건이 없으면 자유롭다고 보기 어렵다.',
    samplePosition:
      '선택지의 수는 자유에 영향을 준다. 그러나 자유는 선택 가능한 조건과 판단 능력도 포함한다. 따라서 현대인이 항상 더 자유롭다고 단정할 수는 없다.',
  },
  {
    id: 'knowledge-experience',
    topic: '지식과 경험',
    level: 'beginner',
    argumentText: '우리가 아는 것은 모두 경험에서 온다. 신은 경험할 수 없다. 그러므로 신에 대해서는 아무것도 알 수 없다.',
    modelClaim: '신에 대해서는 아무것도 알 수 없다.',
    modelReasons: ['우리가 아는 것은 모두 경험에서 온다.', '신은 경험할 수 없다.'],
    hiddenPremise: '경험할 수 없는 대상에 대해서는 어떤 지식도 불가능하다.',
    weakness: '논리적 추론, 증언, 개념 분석 같은 경험 이외의 지식 가능성을 배제한다.',
    sampleCounterargument: '경험할 수 없다는 사실만으로 모든 종류의 지식이 불가능하다고 할 수는 없다.',
    samplePosition:
      '경험은 지식의 중요한 출발점이다. 하지만 인간은 경험뿐 아니라 추론과 개념 분석으로도 생각한다. 그래서 신에 대한 지식 가능성은 경험 문제만으로 끝나지 않는다.',
  },
];
